### ISSUE TITLE
help

### ISSUE THREAD

**Issue by loujainlolo** [AidenFather/Abnormality-Detection-in-Mammography#2]

**Comment by AidenFather** [comment]
I downloaded the 163GB data and developed the model. You need to download the dicom files and convert them into jpg or png files.

**Comment by loujainlolo** [comment]
thanks for your quick reply,can i use only DDSM dataset and try to develop the CNN with it ?because net connection in my country is too slow and i need very long time to download 163 GB

**Comment by AidenFather** [comment]
It's up to you. Explore the DDSM database first and get to know whether they have all cases you want to include in your model such as normal vs. abnormal cases. Good luck!

**Comment by loujainlolo** [comment]
thank u very much for your help and for sharing your code

**Comment by loujainlolo** [comment]
i find this CBIS-DDSM patch on kaggle on this link https://www.kaggle.com/llkihn/ddsm-cbis-patch with only 1GB...can i use it instead of the original CBIS-DDSM if i want to have the five classes

**Comment by AidenFather** [comment]
If you don't want to process the original data, you may use it. However, the datasets are patch images from the original image.

**Comment by loujainlolo** [comment]
i understand,thanks again for u

**Comment by loujainlolo** [comment]
good morning
please i want to ask u about DDSM dataset,I downloaded it with tfrecords format from kaggle and face some problem to convert it to png,
any help with that?
